baseurl             = ""
builddrafts         = false
canonifyurls        = true
relativeURLs        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
pygmentsuseclasses  = true
pluralizelisttitles = false
googleAnalytics     = "UA-42568283-1"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Publications and Talks"
weight                 = -100
identifier             = "publications-and-talks"
url                    = "/publications-and-talks/"

[[menu.main]]
name                   = "Resume"
weight                 = -90
identifier             = "resume"
url                    = "/resume.pdf"

[params]
author       = "David Dias"
title        = "David Dias"
# add the current unix timestamp in query string for cache busting css assets
cachebuster  = false 
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = ""
email        = "mail@daviddias.me"
faviconfile  = "img/favicon.ico"
highlightjs  = true
lang         = "en"
github       = "//github.com/diasdavid"
linkedin     = "//linkedin.com/in/diasdavid"
twitter      = "//twitter.com/daviddias"
selfIntro    = "" # appears in the site header when set to a non-empty string
forcehttps   = false # use a script to detect whether visitors should be redirected to https

# gravatar             = "" # do not use in the same time as avatar
avatar                 = "/img/avatar.jpg"
# highlightjslanguages = ["go"] # additional languages not included in the "common" set
