baseurl             = ""
builddrafts         = false
canonifyurls        = true
relativeURLs        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "David Dias"
title               = "David Dias"
pygmentsuseclasses  = true
pluralizelisttitles = false
googleAnalytics     = "UA-42568283-2"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author       = "David Dias"
# add the current unix timestamp in query string for cache busting css assets
cachebuster  = false 
dateform     = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = ""
email        = "mail@daviddias.me"
faviconfile  = "img/leaf.ico"
github       = "//github.com/diasdavid"
highlightjs  = true
lang         = "en"
linkedin     = "//linkedin.com/in/daviddias"
twitter      = "//twitter.com/daviddias"
selfIntro    = "" # appears in the site header when set to a non-empty string
forcehttps   = false # use a script to detect whether visitors should be redirected to https

# gravatar             = "" # do not use in the same time as avatar
avatar                 = "img/avatar.jpg"
# highlightjslanguages = ["go"] # additional languages not included in the "common" set
