baseURL:
relativeURLs: true
languageCode: en-us
title: David Dias
theme: vanilla-bootstrap-hugo-theme
googleAnalytics: UA-42568283-1
faviconfile: img/favicon.ico

# Uncomment below to enable syntax highlighting
pygmentsCodefences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: pygments

taxonomies:
  tag: tags

permalinks:
  post: blog/:slug/

# See https://feathericons.com - The value of pre is the icon name
menu:
  main:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Blog
    pre: edit
    url: /blog/
    weight: 2
  - name: Tags
    pre: tag
    url: /tags/
    weight: 3
  - name: RSS
    pre: rss
    url: /index.xml
    weight: 4
  - name: About
    pre: zap
    url: /about/
    weight: 5
  - name: Notebook
    pre: book-open
    url: /notebook/
    weight: 6
  - name: Publications and Talks
    pre: bookmark
    url: /publications-and-talks/
    weight: 10
  - name: Mentoring and Teaching
    pre: smile
    url: /mentoring-and-teaching/
    weight: 11
  - name: Resume
    pre: file-plus
    url: /resume.pdf
    weight: 12

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 800px
  dateFormat: Jan 2, 2006
  homeText: Ohai! Welcome to my page. I write here sometimes
  footerText: ♥
